### ISSUE TITLE
[FEATURE] SAML/Shibboleth Authentication

### ISSUE THREAD

**Issue by TS-Daniel16** [KoALa-MHF/koala-app#136]
# Description

Enable username / password login via shibboleth. Rerouting to KoALa app is working and user is authenticated in KoALa app after authenticating with the Shibboleth server. Username is taken as default for display name in KoALa. Display name cannot be changed in the KoALa application.

**Comment by TS-Daniel16** [comment]
SAML authentication working with OneLogin. Shibboleth connection to be clarified and to be implemented.

**Comment by TS-Daniel16** [comment]
Implementation almost finished. Connection to mh Freiburg Shibboleth established and login page can be reached. Issue during SAML response to be clarified, then switch will be done in productive system.

**Comment by TS-Tino16** [comment]
> Implementation almost finished. Connection to mh Freiburg Shibboleth established and login page can be reached. Issue during SAML response to be clarified, then switch will be done in productive system.

Issue solved. MH Freiburg login works now
