### ISSUE TITLE
UX default buttons and double clicks

### ISSUE THREAD

**Issue by mxordn** [KoALa-MHF/koala-app#140]
**Default Buttons/Double click**

In order to improve user exprience I came across two places, where a default button (reacting on pressing Enter) or a double click could be a nice thing to have.

(1) Session Login screen (arrow button after entering a session Code)
(2) Double click on a session entry to enter the session. (Session beitreten)

**Comment by TS-Daniel16** [comment]
Released with version 0.7.7

@mxordn please retest and confirm

**Comment by TS-Daniel16** [comment]
@mxordn closing the issue, as it is included in the above mentioned release. You can reopen it if you find issues with it
