### ISSUE TITLE
Audio continues to play

### ISSUE THREAD

**Issue by s-platte** [KoALa-MHF/koala-app#201]
If you switch from session window to session overview or session info while the audio file is playing, it will continue to play.

1. go to session,
2. play audio,
3. go to session overview / session info while audio is playing.

Audio should pause as soon as you leave the session window.

macOS Ventura 13.3.1 (a)
Chrome 113.0.5672.126
Safari 16.4
Firefox Version 113.0.5672.126

**Comment by TS-Daniel16** [comment]
Released with version 0.7.7

@s-platte please retest and confirm

**Comment by s-platte** [comment]
@TS-Daniel16  The problem still exists in Safari. The audio does not stop when pressing pause or stop button or when leaving the session. Only closing the window can stop the audio. 
Chrome, Firefox and Edge are working. (All browsers only tested on macOS.)

**Comment by TS-Stefan** [comment]
https://github.com/KoALa-MHF/koala-app/pull/293

**Comment by TS-Daniel16** [comment]
@s-platte can you retest this with the newest version deployed to the koala.mh-freiburg.de server and close if it is working for you now

**Comment by s-platte** [comment]
When switching windows, playback now stops in Safari (version 16.5.2 (18615.2.9.11.10)), but in both the Session and Auswertung screens, playback starts immediately once the page has loaded, and still cannot be stopped. As soon as you press stop, playback starts over and when you press pause the start/pause button flickers and nothing happens:

https://github.com/KoALa-MHF/koala-app/assets/116100422/7e889bd3-f7bc-4bea-a9f6-028848406b38

**Comment by TS-Daniel16** [comment]
@TS-Stefan I assigned this back to you. Can you follow up on the error description?

**Comment by TS-Daniel16** [comment]
@s-platte could you retest the newest 0.9.24 version? This should be solved now
