### ISSUE TITLE
Slider marker does not respond on click to new value

### ISSUE THREAD

**Issue by s-platte** [KoALa-MHF/koala-app#202]
Slider marker values only change when you click/tap, hold and slide. In case of tapping / clicking on another value, the slider marker changes its position, but the value in the visuals stay the same.

1. Go to session
2. Play audio
3. Click / Tap on other values on the slider marker
4. Slider marker changes position, but visuals stay the same

Values should also change when clicking / tapping.

macOS Ventura 13.3.1 (a):
- Chrome 113.0.5672.126
- Safari 16.4
- Firefox Version 113.0.5672.126

**Comment by TS-Daniel16** [comment]
Should be resolved with release 0.9.11. Handling of overwriting slider marker values is still open ( #278 ), but recording values with a slider should be correct. Please retest and reopen if still issues persist
