### ISSUE TITLE
Slider marker visuals overlapping

### ISSUE THREAD

**Issue by s-platte** [KoALa-MHF/koala-app#203]
Depending on the chosen range of values, visuals of different markers are overlapping.

1. Create session with different markers (include slider markers e.g. with range 1–10 & range -10–10)
2. Go to session
3. Play audio
4. Annotate with different values of slider markers to see overlap

Values of slider markers should be mapped to available space in visuals.

<img width="258" alt="Bildschirmfoto 2023-05-31 um 15 37 22" src="https://github.com/KoALa-MHF/koala-app/assets/116100422/1eb33b00-0051-4706-83e1-801745b1f8f5">

macOS Ventura 13.3.1 (a)
Chrome 113.0.5672.126
Safari 16.4
Firefox Version 113.0.5672.126

**Comment by TS-Stefan** [comment]
Fixed with https://github.com/KoALa-MHF/koala-app/pull/227

**Comment by TS-Stefan** [comment]
@s-platte please retest and confirm

**Comment by s-platte** [comment]
There is still a small overlap to adjacent marker visualizations. The distance between maximum slider marker values and the adjacent marker visualizations should therefore be increased a bit. (see screenshot)

![Bildschirmfoto 2023-07-04 um 23 19 24](https://github.com/KoALa-MHF/koala-app/assets/116100422/d406f74a-91e1-4ed9-9baa-61e8176166ac)

**Comment by TS-Stefan** [comment]
fixed with https://github.com/KoALa-MHF/koala-app/pull/315

it now automatically scales based on the highest possible value
