### ISSUE TITLE
Start value of slider marker

### ISSUE THREAD

**Issue by s-platte** [KoALa-MHF/koala-app#204]
For a slider marker with a range of 0-10, the visualization automatically starts with a value above zero. If it is returned to zero during the annotation, no line is visible in the visualization. (see screenshot) 

1. Create a session with a slider marker (range 0–10) 
2. Start session
3. Play audio 
4. Wait a couple of seconds to see the default visualization of the slider marker
5. Change the value of the slider marker and then go back to the lowest value (= starting value)
6. Compare visuals to those of the beginning

The visualization should be consistent and should not show any values at the beginning (just an empty line). Only when the slider marker is moved for the first time, the visualization should start.

<img width="249" alt="Bildschirmfoto 2023-05-31 um 15 45 07" src="https://github.com/KoALa-MHF/koala-app/assets/116100422/fd90b9ac-4dd3-470f-9fdb-6b9ce0619e52">

macOS Ventura 13.3.1 (a)
Chrome 113.0.5672.126
Safari 16.4
Firefox Version 113.0.5672.126

**Comment by TS-Stefan** [comment]
fixed with https://github.com/KoALa-MHF/koala-app/pull/317

**Comment by TS-Daniel16** [comment]
Should be fixed with release 0.9.11. Please retest.
