### ISSUE TITLE
No dynamic {{sessionName}} when deleting a session

### ISSUE THREAD

**Issue by tobiashauser** [KoALa-MHF/koala-app#210]
**Describe the bug**
The session name isn't filled when deleting a session

**To Reproduce**
1. Go to 'Meine Sessions'
2. Choose one session
3. Click on 'Session löschen'

**Expected behavior**
"Wollen sie wirklich die Session 'Quinte' löschen?

**Screenshots**
<img width="942" alt="Screenshot 2023-06-03 at 14 50 02" src="https://github.com/KoALa-MHF/koala-app/assets/66157766/0a1772dd-1f21-4fef-b885-da3e2e7e505f">

**Comment by TS-Daniel16** [comment]
Solved with version 0.7.8.

@tobiashauser please retest and close if solved, the version is already deployed to koala-app.de
