### ISSUE TITLE
[BUG] Annotations are not saved

### ISSUE THREAD

**Issue by TS-Daniel16** [KoALa-MHF/koala-app#211]
# Description

When logging in via session code (not user session code), an error message "Annotation could not be saved" appears every time a marker button is pressed in the session screen

**Comment by TS-Daniel16** [comment]
Error comes up because the session owner does not have a user session on their own

@TS-Tino16 could you take this over?

**Comment by TS-Tino16** [comment]
This was fixed by #252 

Reviewed it and works
