### ISSUE TITLE
Annotations are not displayed in Session Analysis Page

### ISSUE THREAD

**Issue by TS-Daniel16** [KoALa-MHF/koala-app#212]
When annotations are created successfully via user session code authentication (at least no error message displayed), the annotations of that user session are not displayed in the session analysis overview page.

**Comment by TS-Daniel16** [comment]
Common storage of start and end time in entities and backend is in ms ... if it is needed to calculate into seconds this should be done in the respective components

**Comment by TS-Stefan** [comment]
fixed with https://github.com/KoALa-MHF/koala-app/pull/315
