### ISSUE TITLE
[BUG] Copy Session should copy markers

### ISSUE THREAD

**Issue by TS-Tino16** [KoALa-MHF/koala-app#222]
**Describe the bug**

When a session is copied, the markers are not copied yet.

**To Reproduce**
1. Go to 'https://koala-app.de/sessions'
2. Click on 'copy session'
3. Navigate to newly created session
4. See error -> markers are not copied

**Expected behavior**
Markers are copied as well

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 N/A

**Additional context**
N/A

**Comment by TS-Daniel16** [comment]
Solved in #229
