### ISSUE TITLE
[FEATURE] Enable "Leave Session" for Participants

### ISSUE THREAD

**Issue by TS-Daniel16** [KoALa-MHF/koala-app#235]
# Description

A user can decide that they want to leave a session in the session overview page. Leaving a session means:

- [x] Maintained annotations stay, but connection to the user is anonymized
- [x] Participant is not listed in session participants list
- [x] Invitations are not send to the user any more
- [x] Dialog is shown to the participant telling the consequences of leaving a session (not able to participate any more)

**Comment by TS-Daniel16** [comment]
@KoALa-MHF/mh-team when a user leaves a session, in which places should their annotations still be visible:

- [ ] Session analysis page?
- [ ] Export?
- [ ] Participant Counter (not directly annotations, but connected to this)
- [ ] Participant Overview List (also not directly annotations, but connected)

**Comment by mxordn** [comment]
After a participant left a session the related data should not be available in any view. @KoALa-MHF/mh-team Am I getting this right?

In the export the data should be added. This is maybe obvious in the data by labeling the dataset of the user as anonymous.
