### ISSUE TITLE
[FEATURE] Export Data from Single Session

### ISSUE THREAD

**Issue by TS-Daniel16** [KoALa-MHF/koala-app#237]
# Description

TO BE CLARIFIED: how should the output data format look like? which data should be included and in which hierarchies

**Comment by TS-Daniel16** [comment]
@KoALa-MHF/mh-team for the export of a session and its annotations we would need a description in which format and which data should be exported.

**Comment by TS-Daniel16** [comment]
Annotation;Type;Start;End;MarkerId;MarkerName;
Annotation1;Event;5000;;
Annotation2;Range;7500;10000;

[{
sessionMae: "Session1",
annotations: [{]}]

**Comment by s-platte** [comment]
When exporting, the following options should be available:

Export one session or export several sessions (by multiple selection). If multiple sessions are exported, one file per session is created and all session files are combined in one zip file. 

In the export window there is the possibility to choose between two file formats: json or csv.

**json:**
Here a database dump is simply saved as json. The structure of the file will be described in the documentation / tutorials. 

filename: sessionname_sessionID.json

**csv:**
The csv file has a semicolon as separator, it has a header and the following structure:

timestamp (in ms); owner_markername1; owner_markername2; user1_ markername1; user1_ markername2 etc. 

The data is then stored per time unit in lines, e.g. like this:
4100; 1;-4;0;-2
4500;1;3;1;3
4100; 0;5;0;4

File name: sessionname_sessionID.csv

**Number formats of marker types:**

Event marker: 0 if not pressed, 1 if pressed
Rangemarker: 0 if not activated, 1 if activated
Slider marker: "Magic number" if not yet pressed and current slider value as soon as slider is moved.

**Comment by TS-Daniel16** [comment]
JSON export is done.
CSV export open

**Comment by TS-Daniel16** [comment]
Part of version 0.9.31
