### ISSUE TITLE
[BUG] error creating new marker

### ISSUE THREAD

**Issue by TS-Stefan** [KoALa-MHF/koala-app#258]
error message 
`Variable \"$createMarker\" got invalid value null at \"createMarker.description\"; Expected non-nullable type \"String!\" not to be null.`

**Comment by TS-Daniel16** [comment]
@TS-Stefan cannot reproduce locally. Can you try deleting your DB and test again?

**Comment by TS-Daniel16** [comment]
Reproducable only with range markers. Here the description field is mandatory in the backend => should be adjusted to the same way as the event marker behaves

**Comment by TS-Daniel16** [comment]
@TS-Stefan closing this, because I cannot reproduce in the newest version (also not for the range marker any more)
