### ISSUE TITLE
Display error of disabled slider marker

### ISSUE THREAD

**Issue by s-platte** [KoALa-MHF/koala-app#281]
If "Bearbeiten“ is disabled, slider markers are not shown grayed out.

![Bildschirmfoto 2023-07-04 um 19 38 15](https://github.com/KoALa-MHF/koala-app/assets/116100422/ea3dfcd0-a97f-485a-a1ec-9bb6ea065357)

All markers should be shown grayed out for users when "Bearbeiten" is disabled.

**Comment by TS-Daniel16** [comment]
@s-platte part of 0.9.0, please recheck and reopen if not working as expected
