### ISSUE TITLE
Marker creation - abbreviation or icon necessary

### ISSUE THREAD

**Issue by s-platte** [KoALa-MHF/koala-app#290]
In the „Marker erstellen“ window, the choice of an icon and/or abbreviation should be mandatory, since either of them is needed for the row labels in Session window and Evaluation window.

**Event Marker & Range Marker:**
Either the abbreviation field or the icon field must be filled in. The descriptions of the abbreviation and icon fields could be changed as follows to indicate that one of them must be filled in:
„Wählen Sie eine Abkürzung und/oder ein Icon für den Marker.“

@KoALa-MHF/mh-team: Is that how you would like this to be done, or do you have any ideas on how to most cleverly communicate this? 

**Slider Marker:**
The Abbreviation field must be a required field.
Here, in the description of the abbreviation field, the „ggf.“ needs to be deleted because the field is mandatory.

**Comment by TS-Daniel16** [comment]
Will be in next release
