### ISSUE TITLE
[FEATURE] Lock deletion function of annotations 

### ISSUE THREAD

**Issue by s-platte** [KoALa-MHF/koala-app#302]
Would it be possible to lock the delete function of annotations via „permissions"? This would be useful for exam situations to prevent examinees from deleting annotations on their own.

**Comment by TS-Daniel16** [comment]
@s-platte would be another setting in the session screen like "editable", "display sample solution", etc. correct? If so, I think we can add it

**Comment by s-platte** [comment]
@TS-Daniel16 exactly – that would be great!

**Comment by TS-Daniel16** [comment]
Included in 0.9.0

@s-platte please test. To have a working translatable text, it might be that you have to clear your browser cache / go into incognito mode
