### ISSUE TITLE
Sessioninfo display problem in session "Camillasso"

### ISSUE THREAD

**Issue by s-platte** [KoALa-MHF/koala-app#303]
No session description is displayed in the Sessioninfo window, although it is existing. The marker descriptions, on the other hand, are displayed for the owner, but not for the user.

Description present (see "Session Settings" window):
![Bildschirmfoto 2023-07-12 um 13 35 36](https://github.com/KoALa-MHF/koala-app/assets/116100422/1ae04d03-4566-4f09-826d-4c2354c9b6ec)

Session description not present (see Session Info window):
![Bildschirmfoto 2023-07-12 um 13 35 54](https://github.com/KoALa-MHF/koala-app/assets/116100422/408c5e80-3cee-4649-8ee9-b5028a59431f)

**Comment by TS-Daniel16** [comment]
Same issue as in the other "navigation" bugs, that when clicking on the navigation in the header area, the wrong session id is taken over into the navigation path (in this example the session has sessionId 40, but the session info page is loaded for sessionId 4

**Comment by TS-Daniel16** [comment]
![Bildschirmfoto 2023-07-16 um 22 33 11](https://github.com/KoALa-MHF/koala-app/assets/99263623/c798c6e0-deb9-49dd-a24e-4c23b002a2a5)

Display for the correct sessionId contains the correct information although without the line breaks => to be checked here as well

**Comment by TS-Daniel16** [comment]
With release 0.9.11 the session description is displayed as expected except for the missing line breaks
