### ISSUE TITLE
Display problems of session window in "Camillasso"

### ISSUE THREAD

**Issue by s-platte** [KoALa-MHF/koala-app#304]
When switching from session to "Sessioninfo" or "Auswertung" as a user (tested on iPad and Mac) and then back to the session, the session no longer appears:

![Bildschirmfoto 2023-07-12 um 13 55 08](https://github.com/KoALa-MHF/koala-app/assets/116100422/2e54a4c7-7af1-46cb-8066-70c7e07787d9)

**Comment by s-platte** [comment]
On the Macbook (as owner), session and evaluation screen appear again, but after a long loading time and with strange display problems. For example, the audio file in the session screen seems to be different from the one in the "Auswertung" screen:

Audio-File Session screen:
![Bildschirmfoto 2023-07-13 um 11 32 25](https://github.com/KoALa-MHF/koala-app/assets/116100422/a1879af2-9b46-4db7-8932-69c7faeb6414)

Audio-File "Auswertung" screen:
![Bildschirmfoto 2023-07-13 um 11 32 58](https://github.com/KoALa-MHF/koala-app/assets/116100422/b12c208d-8f98-462d-9de7-18e9d8881d31)

**Comment by TS-Stefan** [comment]
fixed with https://github.com/KoALa-MHF/koala-app/pull/317

**Comment by TS-Daniel16** [comment]
Assigned to you since you provided the fix. Once we have our next release, we can close it.
