### ISSUE TITLE
Change the label "Analyse" to "Auswertung"

### ISSUE THREAD

**Issue by s-platte** [KoALa-MHF/koala-app#308]
Please change "Analyse" to "Auswertung" in the session settings and permissions:

![Bildschirmfoto 2023-07-12 um 14 31 18](https://github.com/KoALa-MHF/koala-app/assets/116100422/af80ed0a-07c5-48ff-97ed-5a786b7894cb)

![Bildschirmfoto 2023-07-12 um 14 31 03](https://github.com/KoALa-MHF/koala-app/assets/116100422/396b3ed4-5964-4c1d-a58e-78ac51861a4f)

**Comment by TS-Daniel16** [comment]
Release in 0.9.0

@s-platte FYI for retest. Closing this issue, you can reopen it if it is not working as expected
