### ISSUE TITLE
[FEATURE] Allow Participants Access to Session Only in Open/Online State

### ISSUE THREAD

**Issue by TS-Daniel16** [KoALa-MHF/koala-app#326]
# Description

Participants shall only be allowed in sessions which have an open / online status. If it is in preparation, closed or archived (or deleted), participants should not see the session screen / page.

@KoALa-MHF/mh-team what should be shown to the participant and at which point should that be processed. It could already be an error when entering the session code in the input field, or the session page shows instead of the session data a text saying that this session is not yet available. In the session list the session would not be listed until it is open/online.

**Comment by mxordn** [comment]
> https://github.com/orgs/KoALa-MHF/teams/mh-team what should be shown to the participant and at which point should that be processed. It could already be an error when entering the session code in the input field, 

> or the session page shows instead of the session data a text saying that this session is not yet available. In the session list the session would not be listed until it is open/online.

Perferably this one :). The session should not be listed until it is online/available.

**Comment by TS-Daniel16** [comment]
Will be part of release 0.9.33
