### ISSUE TITLE
[FEATURE] Add Global Marker Overview

### ISSUE THREAD

**Issue by TS-Daniel16** [KoALa-MHF/koala-app#327]
# Description

As a new page, there should be next to the "My Sessions" navigation a navigation to enter the global marker maintenance screen. As a first step, this page should list all available marker in the system with their name, description, icon and type.

@KoALa-MHF/mh-team any requests for additional data to be shown in such an overview table of markers? Of course mockups supporting this page, might be helpful.

**Comment by mxordn** [comment]
Sounds good to us (@TaSpatzHfM, @mxordn).

**Comment by s-platte** [comment]
Which functions should be included in the global marker maintenance screen? Deleting individual markers from the marker pool would only be possible if they are not used in a session, and this would only apply to markers in deleted sessions. Therefore, I wonder if this extra page is necessary at all. Access to the marker pool is already available during marker creation. We could, for example, gray out those markers that are only assigned to deleted sessions and allow them to be deleted in this screen. @KoALa-MHF/mh-team: How is your view on this?

**Comment by TS-Daniel16** [comment]
@s-platte current offer was for marker creation and overview. We would have added a copy and update in this view as well (for free so to say ;-)), but deletion was out of scope for this, because of the hard definition of when and how to delete (getting an overview of all connected sessions might then be required, etc.). The above mentioned points would be the big difference to today's marker maintenance in the session:

1. You can maintain markers without a session, so you can create a pool of markers upfront
2. Copy markers and adjust them
3. Update existing markers

Since we thought the decision to go for the global marker maintenance was already decided, would be good if you give us feedback very soon if that is still wanted before we continue working on this

P.S.: this issue is only about the display, the creation is described in issue #328. Copy and update would be additional issues depending on your decision

**Comment by TS-Daniel16** [comment]
Agreed behavior: new page on level of "My sessions" which lists the markers in a table. Behavior of create, update and copy is described in separate issues

**Comment by TS-Daniel16** [comment]
#362
