### ISSUE TITLE
[FEATURE] Do not Record/Overwrite Hidden Slider

### ISSUE THREAD

**Issue by TS-Daniel16** [KoALa-MHF/koala-app#333]
# Description

A slider normally always records a value as soon as the session is started/restarted. Through issue #278 sliders will overwrite existing annotations when audio is restarted/reset position. In case of a hidden slider marker, the behavior should be that existing annotations are not overwritten/deleted to support a scenario where multiple session runs are executed, but with different markers to focus on.

@KoALa-MHF/mh-team is our definition of that behavior also ok from your side?

**Comment by s-platte** [comment]
Similar to #334, also in the case of replaying the audio file, the values already entered should not be overwritten until the slider is moved. This also ensures that existing annotations are not automatically overwritten with the current slider value. As far as I remember, we had discussed the use of a "magic number" also in case of gaps. I.e. if the user jumps to a distant point in the piece, the timeline up to that point is not automatically filled with the current slider value, but remains empty (also using the "magic number" which is linked to an empty visualization).

@KoALa-MHF/mh-team: Do you agree with this?

**Comment by TS-Daniel16** [comment]
Obsolete with the behavior described in #278. Slider will only overwrite if moved. Since it is not moved when it is hidden, no values will be overwritten by a hidden slider.
