### ISSUE TITLE
[FEATURE] Default Value Definition for Slider Marker

### ISSUE THREAD

**Issue by TS-Daniel16** [KoALa-MHF/koala-app#334]
# Description

For a slider marker a user can define the minimum and maximum value the slider can provide. In case of ranges which does not include the value 0 (e.g. min = 2, max = 5), the default value at the beginning of the audio file would be the minimum value always.

@KoALa-MHF/mh-team is there a need to define a default value from the user's side?

**Comment by s-platte** [comment]
Since each value of the slider has a meaning, starting at the minimum value by default would be problematic. Therefore, when the piece is played, values should not be recorded until the slider is moved. Until then, a "magic number" could be written, and the visualization should remain empty.

**Comment by TS-Daniel16** [comment]
Since the recording should not automatically start, we would recommend to skip this topic and always put the slider to the start position on the left in the beginning. When the slider has been changed and there is a pause and restart, the slider would not be put to the left position, but just stays where it was left (of course not directly recording as discussed).

@KoALa-MHF/mh-team sounds good for you? I am closing this issue, if you see it differently than described above, please reopen again
