### ISSUE TITLE
Region Annotation is not saved

### ISSUE THREAD

**Issue by mxordn** [KoALa-MHF/koala-app#339]
In the Session Semi-Final-1 (ID 51) the Region Marker "E" can be activated. After starting an annotation the region is drawn in the timeline, but on hitting the button to stop the region, annotations aren't saved.  A red toast message appears saying "Konnte nicht gespeichert werden".

<img width="1440" alt="Bildschirm­foto 2023-07-19 um 12 42 09" src="https://github.com/KoALa-MHF/koala-app/assets/451759/fcd7f4ee-5cf6-4c65-83bd-88e99091a122">

**Comment by TS-Daniel16** [comment]
Already fixed in #330. Release pending.

**Comment by TS-Daniel16** [comment]
@mxordn is part of the newest releases (latest 0.9.5), could you retest and close if it is working ok?
