### ISSUE TITLE
[FEATURE] Domain SSL Encryption

### ISSUE THREAD

**Issue by mxordn** [KoALa-MHF/koala-app#34]
The domain koala-app.de has a valid SSL Certificate coming from the registrar.

- [x] SSL Certificate for https Protocol

**Comment by TS-Daniel16** [comment]
@mxordn is the certificate already in use in the nginx so that we can close this issue?

**Comment by mxordn** [comment]
> @mxordn is the certificate already in use in the nginx so that we can close this issue?

Nginx is using the certificate. Stefan merged the different confs into one. Let's close this issue.
