### ISSUE TITLE
coupling annotation from the player (users) / decoupling owners player 

### ISSUE THREAD

**Issue by mxordn** [KoALa-MHF/koala-app#340]
In case users can use their player individually to make annotations, at the moment, starting the player on users side does not enable the annotation buttons on the user's screen (e.g. in Session 51). The markers only are activated for users if the owner starts the soundfile for everybody.

That leads to a second point:
Same case users are working on their own. At the moment the owner still can start/stop the audio file by pressing play stop on his/her machine. This should be decoupled/unsubscribed if users are allowed to use the player on their on and should be coupled again, if the owner wants to take back.

**Comment by TS-Daniel16** [comment]
@mxordn If player is enabled for participant, the owner does not control the players of the participants, but the participants need to start the player themselves to create annotations. Please retest
