### ISSUE TITLE
Include filter and sorting in "marker library" (on marker creation page) 

### ISSUE THREAD

**Issue by s-platte** [KoALa-MHF/koala-app#341]
Would it be possible to integrate a function to sort the marker list alphabetically by marker name? Additionally, it would be helpful to filter markers by type, e.g. to display only slider markers.

**Comment by TS-Daniel16** [comment]
@s-platte we can add a static sorting for the marker list, so that it will always be sorted alphabetically. Is that what you had in mind?

Regarding the filter we will check options to do so

**Comment by TS-Daniel16** [comment]
#362 adds filters for type, description and name

**Comment by TS-Daniel16** [comment]
@s-platte friendly reminder about the sorting question

**Comment by s-platte** [comment]
@TS-Daniel16 Yes, it would be great if we could sort the entries in ascending or descending order by clicking on the arrows in the header of the table. Here is an example from PrimeNG (table sort):
<img width="869" alt="Bildschirmfoto 2023-08-04 um 10 45 54" src="https://github.com/KoALa-MHF/koala-app/assets/116100422/0cdafb8a-2259-4162-9e76-15b48fc4341e">

**Comment by TS-Daniel16** [comment]
@s-platte added with release 0.9.11
