### ISSUE TITLE
[FEATURE] Marker Attributes/Design

### ISSUE THREAD

**Issue by mxordn** [KoALa-MHF/koala-app#36]
After our discussion yesterday this is what I kept in mind:

### Marker attributes
- How are Marker managed (mockups are on the way :))
- The current marker attributes are:
    - icon
    - display text
    - color
    - type (event/region, slider version needs to be discussed, if possible)
- [new] After the discussion yesterday a short description should be added to the attributes

### Marker usage
- It should be possible to record a Marker multiple times as you hear the piece more than once (two or more tries for users are rather normal)
- It should be possible to record a region marker with overlapping regions.

**Comment by TS-Daniel16** [comment]
Basic marker maintenance for a session completed. The following behavior is implemented:

- There are two types of markers: event and range (slider marker will be handled separately)
- Event markers are half the width of a range marker
- A marker can have the following attributes maintained:
  * Type
  * Name (non-unique)
  * Description
  * Abbreviation (which is shown in the button; can be two characters long for an event marker and six characters long for a range marker)
  * Color
  * Icon
- A marker can exist of only an icon, or only an abbreviation text or both
- Markers can be repositioned by drag&drop in the placement area on the right side
- A marker preview is presented in the mid area of the screen; buttons to reset the entered data as well as a button to add it to the session are next to it
- Marker assignments to a session are directly saved and do not need to be confirmed; same applies to the reordering of markers, no additional "save" action required
- Markers are presented in a row and are wrapped either when space is not enough any more or if six "cells" are consumed (1 cell being the width of an event marker)

Open points of marker maintenance which will be addressed in dedicated Github issues:
- Removing a marker from a session

Marker usage to create annotations (described in "Marker usage" in this issue) will be handled separately in new Github issues.

**Comment by TS-Daniel16** [comment]
Release pending

**Comment by TS-Daniel16** [comment]
Release available (v0.5), closing issue
