### ISSUE TITLE
Asynchronous session: marker are deactivated 

### ISSUE THREAD

**Issue by tobiashauser** [KoALa-MHF/koala-app#371]
**Describe the bug**
The markers are only active if the session host plays the audio file. That means sessions can not be done asynchronously.

**To Reproduce**
Participate in this session to experience the issue: [Testsession](https://koala.mh-freiburg.de/auth?sessionCode=m8nWKVV)

1. Create a session, allow **Bearbeitung** and **Player** under **Freigaben**
2. As participant in the session (via link) play the audio
3. Markers are still deactivated

**Expected behavior**
Markers are active.

**Desktop:**
 - OS: macOS, Windows
 - Browser Chrome, Edge

**Comment by TS-Daniel16** [comment]
Duplicate to #340 => closing
