### ISSUE TITLE
Jumping back in the audio breaks the participants' audio

### ISSUE THREAD

**Issue by tobiashauser** [KoALa-MHF/koala-app#373]
**Describe the bug**
Jumping backwards in the audio breaks the participants' audio. 
See the screen recording below.

**To Reproduce**
1. Open a session. Deactivate **Player** in **Freigaben**. 
2. Start playing the audio
3. Skip backwards
4. See the error in the participant

**Expected behavior**
I expect the audio to skip backwards for the participant as well.

**Screenshots**
On the left is the host, on the right the participant:

https://github.com/KoALa-MHF/koala-app/assets/66157766/5f5f16be-ca04-4358-9542-38e8b266f747

**Desktop:**
 - OS: macOS
 - Browser Chrome

**Comment by TS-Daniel16** [comment]
@TS-Stefan this seems to be similar to the seeking issue for annotation ends

**Comment by TS-Daniel16** [comment]
Fixed with #483 
Will be part of release 0.9.33

**Comment by TS-Daniel16** [comment]
@tobiashauser this should be solved now (release 0.9.33 which was just installed on the server). You can retest it.
