### ISSUE TITLE
Lack of correspondence of marker order

### ISSUE THREAD

**Issue by markusrombach07** [KoALa-MHF/koala-app#388]
Moving a marker on the marker page does not change the placement of the corresponding annotation line in the session display. Consequently, this should also change according to the drag & drop movement.

<img width="410" alt="Bildschirm­foto 2023-08-08 um 16 31 06" src="https://github.com/KoALa-MHF/koala-app/assets/116374471/121482c2-a805-4c15-8bf9-8e13ae360225">

<img width="1277" alt="Bildschirm­foto 2023-08-08 um 16 30 32" src="https://github.com/KoALa-MHF/koala-app/assets/116374471/c0e782c3-1e04-48c7-9ce0-b6da405b9e5d">

**Comment by TS-Daniel16** [comment]
@TS-Stefan saw a sort statement for the marker annotation line sequence. Any reason for that sort statement? Otherwise the sorting order from the toolbar should be taken over

**Comment by TS-Daniel16** [comment]
@markusrombach07 As discussed today, the fix is available with version 0.9.25 which is installed on the website. Closing this issue, please reopen if you face further problems with this topic.
