### ISSUE TITLE
Recording isn't stopping

### ISSUE THREAD

**Issue by mxordn** [KoALa-MHF/koala-app#400]
**Describe the bug**
After starting the recording as owner the recording doesn't stop after hitting stop button. In these cases the Success message is not printed in the browser console.

**To Reproduce**
1. Start a session
2. Click on play
3. Click on stop
4. In some cases you see/hear the error

It is more likely to have the error, if you try to start the recording from somewhere in the middle of the recording.

If you scratch with the mouse over the recording timeline, you see the client jumping from the expected position to the end very fast.

**Expected behavior**
The recording should always stop after hitting the stop button

**Comment by TS-Daniel16** [comment]
@mxordn should be solved with the currently deployed version. Please retest.
