### ISSUE TITLE
clients and owner not in sync

### ISSUE THREAD

**Issue by mxordn** [KoALa-MHF/koala-app#401]
**Description**
If you want to start the recording as owner at a position other than from the beginning, the clients do not follow to this specific position. Instead the client jumps to the end of the recording. As a result no annotations are recorded for the clients in this case.

**Steps to reproduce the behavior:**
1. Start a Session
2. Jump to a certain position in the Audiofile (as owner)
3. You can see that the client jumps to the end of the recording
4. after hitting play no annotations can be saved by the client 

**Expected behavior**
Playhead position should jump to the correct position on the client side.

**Comment by TS-Daniel16** [comment]
Participants now get only sync updates from the current audio position every 5 seconds. During these 5 seconds, the participants clients "play" their own audio (without sound) to have the correct position of annotations and current audio position.
