### ISSUE TITLE
[FEATURE] Marker Color Input Via Hex Code

### ISSUE THREAD

**Issue by TS-Daniel16** [KoALa-MHF/koala-app#422]
# Description

To be able to have the exact same color for multiple markers, it should be possible to copy the hex code from one markers' color to another markers' color.

**Comment by TS-Daniel16** [comment]
Idea would be as shown here:

![Bildschirmfoto 2023-10-13 um 18 49 28](https://github.com/KoALa-MHF/koala-app/assets/99263623/54307ca2-be4a-4e76-9349-7971eeb14bef)

![Bildschirmfoto 2023-10-13 um 18 49 31](https://github.com/KoALa-MHF/koala-app/assets/99263623/c8a94287-2aa6-4f00-9fda-82e31c975f8f)

Input field updates when color is picked through the color picker. Color picker adjusts when a new hex code is entered and enter is pressed.
@KoALa-MHF/mh-team ok from your side?

**Comment by s-platte** [comment]
That's perfect!

**Comment by TS-Daniel16** [comment]
Released with version 0.9.24
