### ISSUE TITLE
Slider marker: annotation not set right, when "seeking" 

### ISSUE THREAD

**Issue by TS-Tino16** [KoALa-MHF/koala-app#432]
**Describe the bug**

Slider marker: annotation not set right, when "seeking" -> annotation is longer then expected

**To Reproduce**

1. Go to a session with a slider marker
2. Start the session
3. Increase the slider marker
4. Seek to a previous position
5. See Error

**Expected behavior**

Slider annotation should be only logged until previous position before seeking

**Comment by TS-Daniel16** [comment]
Solved in 0.9.24
