### ISSUE TITLE
client cursor moving on entering session

### ISSUE THREAD

**Issue by mxordn** [KoALa-MHF/koala-app#434]
Maybe already reported these days.

In some cases the clients player cursor starts moving when the client user enters the session. The Player is not giving sound, but cursor is moving automatically without being able to stop it, because the player . The owners activated „Bearbeiten“ and „In Bearbeitung“ but nor „Player“.

We observed that this behaviour changed after the owner entered the session. Maybe there are some parameters not set, before the owner is online?

**Comment by TS-Daniel16** [comment]
@mxordn we couldn't reproduce it locally. So if this situation happens again, please reopen the issue with potentially a sample session (id or name) for us to look into it.
