### ISSUE TITLE
Audio Commentary (AudiKom)

### ISSUE THREAD

**Issue by mxordn** [KoALa-MHF/koala-app#437]
# AudiKom

## Feature Description
Audio commentary are handled similiar to text comments.

### Creating a comment 
By clicking on an annotation a dialog pops up asking the user to add either text or audio comments (as visualized in mockup).

After the user chose audio comment the dialog for recording an audio file opens up. The dialog contains two buttons for recording and playing the comment. As long as no audio is recorded the play button should be disabled.
Clicking on the record button starts recording and the button turns into a stop recording button. Recordings can be limited to 5 minutes, if this adds something to stability.
The dialog can be closed by hitting „save/Speichern“ for adding the comment to the annotation or the dialog can be dismissed by clicking „cancel/Abbrechen“

### Reading/Listening to comments

All comments for a single annotation can be viewed by clicking on the annotation. All associated comments are listed below the „create new“-Buttons. This was not part of the mockup so far. The users can click on an entry in the list to view and listen to the comments. 

Audio comments in the list are displayed with a play/pause toggle at the right end of the line in order to be able to play the comment right from this place. Text comments extend the dialog to the right and text is shown in the space there.

### Deleting a comment
Only the creators of a comment. Therefore list of comments contains a red „x“ at the beginning of the line.

## Session archive/delete
- Moving a session to the archive keeps all comments available.
- Deleting a session hard deletes all associated comments.

## Comment handling in the session

- Comments to annotations are indicated by a small speech bubble. In the mockup the comments were symbolized by a "T" or a speaker icon. This can be simplified by just having one icon indicating that there are comments.
- The owner should be able to activate/deactivate all the comment functionality (create/read/delete) for all participants in a session at any time. This should be part of the session preferences (Session Einstellungen)
    - The owner always sees the existing comments and can view/play them.

**Comment by TS-Daniel16** [comment]
First version of audio comment part of 0.9.26 (deployed today). Missing part is visualization of existing audio comment (or text comment for that matter) on the annotation

**Comment by TS-Daniel16** [comment]
Audio comment and visualization of existing comment (audio or text) is completed.
