### ISSUE TITLE
[FEATURE] Introduce Second Option for SAML Auth Provider

### ISSUE THREAD

**Issue by TS-Daniel16** [KoALa-MHF/koala-app#449]
# Description

Additionally to the Shibboleth based SAML user authentication, Koala should also be able to handle a second SAML provider in addition.

- OneLogin should be possible to be added as second option
- A second login button will be added to the login page leading to the OneLogin login page authenticated a user
- The user then acts as a "normal" authenticated user (can create sessions, etc.)

**Comment by TS-Daniel16** [comment]
Add frontend environment variable to control visibility of second login button

Menubutton with default option for Shibboleth

**Comment by TS-Tino16** [comment]
Tested and works on live system
