### ISSUE TITLE
Markers of the toolbox are not shown as annotationg

### ISSUE THREAD

**Issue by TaSpatzHfM** [KoALa-MHF/koala-app#470]
Since using the new login (one-login), the markers overtaken from the existing markers are not shown on annotating on the side of the user. They are shown in the Auswertungs-Screen. This is not the case for new markers that have been created in the existing session; there you can see the annotations. (The pre-existing markers were created inside the new login, but in a different session)

**Comment by TS-Daniel16** [comment]
@TaSpatzHfM we could not replicate this behavior. Please reopen if situation happens again and you have a concrete session in which we can have a closer look.
