### ISSUE TITLE
Log-in with Session Code isn't working anymore 

### ISSUE THREAD

**Issue by TaSpatzHfM** [KoALa-MHF/koala-app#490]
Log-in with the Session Code doesn't work anymore.
Log-in through invitation per Mail is working. 
Session is online and open 
(under using the "new" login under one-login)

**Comment by WolfgangDrescher** [comment]
I can confirm this. Entering a session with a session code did not work. I just tested with in classes with some students.

**Comment by TS-Daniel16** [comment]
Most likely related to email conversion (to lower), which is not applicable in anonymous logins

**Comment by TaSpatzHfM** [comment]
One observation concerning the codes: 
With every invitation per Mail to a Session, there is generated a new session-code different from the one shown in the Session-Übersicht. The Code changes every time with sending a new mail invitation. With the code shown on clicking on the link in the mail invitation, login via Code is possible (also without getting an e-Mail, until an new Mail and therefore a new code is linked to the session)

**Comment by TS-Daniel16** [comment]
Part of release 0.9.39

**Comment by TS-Daniel16** [comment]
@TaSpatzHfM with release 0.9.39 this issue should be fixed. Can you retest and if it does not yet work for you reopen the issue?
