### ISSUE TITLE
State changes when audio finished playing

### ISSUE THREAD

**Issue by WolfgangDrescher** [KoALa-MHF/koala-app#494]
If the audio has finished playing the needle of the sound wave will stay at the end but the slider/needle of the markers section will disappear. Also the play/pause button does not change it's state when the audio has finished.

Also when the audio is paused the slider/needle above the markers does not change its position when seek the audio file by clicking on the sound wave, but only when playback is resumed.

**Comment by TS-Daniel16** [comment]
@TS-Stefan could you have a look. Seems like the wavesurfer event for "end" does not stop the timeline "needle"

**Comment by TS-Daniel16** [comment]
@WolfgangDrescher we have released a new version with a fix for your reported situation. Could you retest if it is working now as expected for you?
