### ISSUE TITLE
„Fehler“ on using Audiokommentar under Safari

### ISSUE THREAD

**Issue by TaSpatzHfM** [KoALa-MHF/koala-app#500]
- on using Audiokommentar under Safari, recording and listening to comments (recorded under Chrome) not possible; the player shows: „Fehler“ 
- under chrome, recording and listening to recorded comments is possible without problems

**Comment by TS-Daniel16** [comment]
Fixed with 0.9.42, audio files are now stored as mp3. @TaSpatzHfM this should work now in Safari, old audio comments might still not work, because of the different audio format, but for newly created comments it should work fine
