### ISSUE TITLE
Missing HTTPS redirect

### ISSUE THREAD

**Issue by WolfgangDrescher** [KoALa-MHF/koala-app#505]
http://koala.mh-freiburg.de/ does not redirect to HTTPS.

**Comment by TS-Daniel16** [comment]
@mxordn yes, you can change that, should not affect anything

**Comment by mxordn** [comment]
Redirect is set. Could you please test it and report it here, if the change broke any functionality.

**Comment by WolfgangDrescher** [comment]
Works for me now. Thank you.
