### ISSUE TITLE
"Auswertung" für User 

### ISSUE THREAD

**Issue by TaSpatzHfM** [KoALa-MHF/koala-app#508]
If "Auswertung" is open for users: 
User clicks on "Auswertung" Screen and the session status is changed to "imAufbau"; user sees "Session noch nicht gestartet"
If Session is set to "online" by the owner, user just sees his own annotations and not the others, also not the annotations of the Owner if "Musterlösung" is opened up

**Comment by TS-Daniel16** [comment]
Seeing other users annotations in the analysis screen is by design. The sample solution part is a bug which we are currently working on

**Comment by TS-Daniel16** [comment]
@TaSpatzHfM we have released fixes that you can see now the sample solution as a participant and that the session status is not reset to in preparation by accident (e.g. clicking on the analysis button)
