### ISSUE TITLE
Audiokommentare are following up one another 

### ISSUE THREAD

**Issue by TaSpatzHfM** [KoALa-MHF/koala-app#522]
using Audiokommentar under chrome: 
- first audio comment is saved, shown and can be played 
- if button "verwerfen" is used and on retaking another audio comment, both of them are stringed together and played one after the other 
- the same is happening with all the audio comments recorded in one session 
- if I leave the session and login again, I start from the beginning

**Comment by TS-Daniel16** [comment]
Fixed with #521 ... will be included in next release

**Comment by TS-Daniel16** [comment]
Related to #500

**Comment by TS-Daniel16** [comment]
Fixed with 0.9.42 release
@TaSpatzHfM this should be resolved now, you can go ahead and retest
